//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyRecipeBook.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMessagesExceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessagesExceptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyRecipeBook.Exceptions.ResourceMessagesExceptions", typeof(ResourceMessagesExceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one ingredient is required to proceed..
        /// </summary>
        public static string AT_LAST_ONE_INGREDIENT {
            get {
                return ResourceManager.GetString("AT_LAST_ONE_INGREDIENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one instruction is required to proceed..
        /// </summary>
        public static string AT_LAST_ONE_INSTRUCTION {
            get {
                return ResourceManager.GetString("AT_LAST_ONE_INSTRUCTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value not supported..
        /// </summary>
        public static string COOKING_TIME_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("COOKING_TIME_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Difficulty not supported..
        /// </summary>
        public static string DIFFICULTY_LEVEL_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("DIFFICULTY_LEVEL_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected dish type is not supported..
        /// </summary>
        public static string DISH_TYPE_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("DISH_TYPE_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicated ingredients are not allowed in the list..
        /// </summary>
        public static string DUPLICATED_INGREDIENTS_IN_LIST {
            get {
                return ResourceManager.GetString("DUPLICATED_INGREDIENTS_IN_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already registered..
        /// </summary>
        public static string EMAIL_ALREADY_REGISTERED {
            get {
                return ResourceManager.GetString("EMAIL_ALREADY_REGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The e-mail must nao be empty..
        /// </summary>
        public static string EMAIL_EMPITY {
            get {
                return ResourceManager.GetString("EMAIL_EMPITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already registered..
        /// </summary>
        public static string EMAIL_INVALID {
            get {
                return ResourceManager.GetString("EMAIL_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email and/or password.
        /// </summary>
        public static string EMAIL_OR_PASSWORD_INVALID {
            get {
                return ResourceManager.GetString("EMAIL_OR_PASSWORD_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ingredient list cannot be empty..
        /// </summary>
        public static string INGREDIENT_EMPTY {
            get {
                return ResourceManager.GetString("INGREDIENT_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ingredient format. Please ensure the ingredient follows our pattern..
        /// </summary>
        public static string INGREDIENT_NOT_FOLLOWING_PATTERN {
            get {
                return ResourceManager.GetString("INGREDIENT_NOT_FOLLOWING_PATTERN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The instruction list cannot be empty..
        /// </summary>
        public static string INSTRUCTION_EMPTY {
            get {
                return ResourceManager.GetString("INSTRUCTION_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instruction exceeds maximum character limit..
        /// </summary>
        public static string INSTRUCTION_EXCEEDS_LIMIT_CHARACTERS {
            get {
                return ResourceManager.GetString("INSTRUCTION_EXCEEDS_LIMIT_CHARACTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid number of ingredients. The list must contain between 1 and 5 ingredients..
        /// </summary>
        public static string INVALID_NUMBER_INGREDIENTS {
            get {
                return ResourceManager.GetString("INVALID_NUMBER_INGREDIENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name cannot be empty..
        /// </summary>
        public static string NAME_EMPITY {
            get {
                return ResourceManager.GetString("NAME_EMPITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No token here..
        /// </summary>
        public static string NO_TOKEN {
            get {
                return ResourceManager.GetString("NO_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The step number in the instruction cannot be less than zero..
        /// </summary>
        public static string NON_NEGATIVE_INSTRUCTION_STEP {
            get {
                return ResourceManager.GetString("NON_NEGATIVE_INSTRUCTION_STEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only images (PNG, JPG, JPEG) are accepted..
        /// </summary>
        public static string ONLY_IMAGES_ACCEPTED {
            get {
                return ResourceManager.GetString("ONLY_IMAGES_ACCEPTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password different from current password..
        /// </summary>
        public static string PASSWORD_DIFFERENT_CURRENT_PASSWORD {
            get {
                return ResourceManager.GetString("PASSWORD_DIFFERENT_CURRENT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password must be longer than 6 caracters..
        /// </summary>
        public static string PASSWORD_EMPITYB {
            get {
                return ResourceManager.GetString("PASSWORD_EMPITYB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password must be longer than 6 caracters..
        /// </summary>
        public static string PASSWORD_INVALID {
            get {
                return ResourceManager.GetString("PASSWORD_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipe not found..
        /// </summary>
        public static string RECIPE_NOT_FOUND {
            get {
                return ResourceManager.GetString("RECIPE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title cannot be empty..
        /// </summary>
        public static string RECIPE_TITLE_EMPTY {
            get {
                return ResourceManager.GetString("RECIPE_TITLE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two or more instructions have the same order..
        /// </summary>
        public static string TWO_OR_MORE_INSTRUCTIONS_SAME_ORDERS {
            get {
                return ResourceManager.GetString("TWO_OR_MORE_INSTRUCTIONS_SAME_ORDERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error..
        /// </summary>
        public static string UNKNOWN_ERROR {
            get {
                return ResourceManager.GetString("UNKNOWN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user does not have permission to access the resource..
        /// </summary>
        public static string USER_WITHOUT_PERMISSION_ACCESS_RESOURCE {
            get {
                return ResourceManager.GetString("USER_WITHOUT_PERMISSION_ACCESS_RESOURCE", resourceCulture);
            }
        }
    }
}
